-- Business OS MVP: AI CEO roles, daily reports, business type

-- Business type on companies (universal model: restaurant, dental clinic, etc.)
ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS business_type text NOT NULL DEFAULT 'other';

-- AI role on chat conversations (CEO / CFO / HR / CMO)
ALTER TABLE public.chat_conversations
  ADD COLUMN IF NOT EXISTS ai_role text NOT NULL DEFAULT 'ceo';

-- Daily reports generated by AI CEO
CREATE TABLE public.daily_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  content text NOT NULL,
  metrics jsonb NOT NULL DEFAULT '{}',
  generated_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, report_date)
);

CREATE INDEX daily_reports_company_date_idx
  ON public.daily_reports (company_id, report_date DESC);

ALTER TABLE public.daily_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY daily_reports_select ON public.daily_reports
  FOR SELECT USING (company_id IN (SELECT public.user_company_ids()));

CREATE POLICY daily_reports_insert ON public.daily_reports
  FOR INSERT WITH CHECK (company_id IN (SELECT public.user_company_ids()));

CREATE POLICY daily_reports_update ON public.daily_reports
  FOR UPDATE USING (company_id IN (SELECT public.user_company_ids()));

CREATE POLICY daily_reports_delete ON public.daily_reports
  FOR DELETE USING (company_id IN (SELECT public.user_company_ids()));
